package com.billcreator.invoice.invoicegenerator.invoicemaker.Database

object Query {
    private const val COMMA_SEP = ","
    private const val FLOAT_TYPE = " REAL"
    private const val FOREIGN_KEY_CONSTRAINT = " FOREIGN KEY"
    private const val INT_TYPE = " INTEGER"
    var SELECT_ALL_FROM_BUSINESS_INFORMATION = "SELECT * FROM BUSINESS_INFORMATION"
    var SELECT_ALL_FROM_CLIENTS = "SELECT * FROM CLIENTS"
    var SELECT_ALL_FROM_ITEMS = "SELECT * FROM ITEMS"
    var SELECT_ALL_FROM_SETTINGS = "SELECT * FROM SETTINGS"
    var SELECT_CATALOGS_BY_CLIENT =
        "SELECT * FROM CATALOG WHERE PAID_STATUS = ? AND TYPE = ? AND CLIENTS_ID = ?"
    var SELECT_CATALOG_BY_CLIENT =
        "SELECT SUM(TOTAL_AMOUNT) as TOTAL_AMOUNT, SUM(PAID) as PAID, COUNT(_id) as TOTAL_CATALOG  FROM CATALOG WHERE TYPE = ? AND CLIENTS_ID = ?"
    var SELECT_CATALOG_IMAGES = "SELECT * FROM CATALOG_IMAGES WHERE CATALOG_ID = ?"
    var SELECT_CREATION_DATE_FROM_INVOICES = "SELECT CREATED_AT FROM CATALOG"
    var SELECT_ESTIMATES_FROM_CATALOG = "SELECT * FROM CATALOG WHERE TYPE = 1"
    var SELECT_INVOICES_FROM_CATALOG = "SELECT * FROM CATALOG WHERE TYPE = 0"
    var SELECT_INVOICE_ITEMS_ASSOCIATED = "SELECT * FROM ITEMS_ASSOCIATED WHERE CATALOG_ID = ?"
    var SELECT_INVOICE_PAYMENTS = "SELECT * FROM PAYMENTS WHERE CATALOG_ID = ?"
    var SELECT_INVOICE_SHIPPING = "SELECT * FROM SHIPPING WHERE CATALOG_ID = ?"
    var SELECT_PAID_FROM_CATALOG = "SELECT * FROM CATALOG WHERE PAID_STATUS = ? AND TYPE = ?"
    var SELECT_SINGLE_CATALOG = "SELECT * FROM CATALOG WHERE _id = ?"
    var SELECT_SINGLE_CLIENT = "SELECT * FROM CLIENTS WHERE _id = ?"
    internal const val SQL_CREATE_ENTRY_BUSINESS_INFORMATION =
        "CREATE TABLE BUSINESS_INFORMATION (_id INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,REGISTRATION_NUMBER TEXT,VAT TEXT,ADDRESS_LINE_1 TEXT,ADDRESS_LINE_2 TEXT,ADDRESS_LINE_3 TEXT,PHONE TEXT,MOBILE TEXT,FAX TEXT,EMAIL TEXT,WEBSITE TEXT,LOGO_URL TEXT,PAYPAL_ADDRESS TEXT,CHEQUES_INFORMATION TEXT,BANK_INFORMATION TEXT,OTHER_PAYMENT_INFORMATION TEXT,TAXES INTEGER,FULLY_PAID INTEGER,INVOICE_NOTES TEXT,ESTIMATE_NOTES TEXT,QTY_RATE INTEGER ) "
    internal const val SQL_CREATE_ENTRY_CATALOG =
        "CREATE TABLE CATALOG (_id INTEGER PRIMARY KEY AUTOINCREMENT,CLIENTS_ID INTEGER DEFAULT 0,TYPE INTEGER,DISCOUNT_TYPE INTEGER,TAX_TYPE INTEGER,TAX_LABEL TEXT,TAX_RATE REAL,NAME TEXT,CREATED_AT TEXT,TERMS INTEGER,DUE_DATE TEXT,PO_NUMBER TEXT,DISCOUNT REAL,PAID REAL,TOTAL_AMOUNT REAL,PAID_STATUS INTEGER,ESTIMATE_STATUS INTEGER,SIGNED_DATE TEXT,SIGNED_URL TEXT,NOTES TEXT ) "
    internal const val SQL_CREATE_ENTRY_CATALOG_IMAGES =
        "CREATE TABLE CATALOG_IMAGES (_id INTEGER PRIMARY KEY AUTOINCREMENT,CATALOG_ID INTEGER,IMAGE_URL TEXT,DESCRIPTION TEXT,ADDITIONAL_DETAILS TEXT, FOREIGN KEY ( CATALOG_ID )  REFERENCES CATALOG ( _id ) ON DELETE CASCADE) "
    internal const val SQL_CREATE_ENTRY_CLIENTS =
        "CREATE TABLE CLIENTS (_id INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,EMAIL TEXT,MOBILE TEXT,PHONE TEXT,FAX TEXT,ADDRESS_CONTACT TEXT,ADDRESS_LINE_1 TEXT,ADDRESS_LINE_2 TEXT,ADDRESS_LINE_3 TEXT,SHIPPING_ADDRESS_NAME TEXT,SHIPPING_ADDRESS_LINE_1 TEXT,SHIPPING_ADDRESS_LINE_2 TEXT,SHIPPING_ADDRESS_LINE_3 TEXT ) "
    internal const val SQL_CREATE_ENTRY_ITEMS =
        "CREATE TABLE ITEMS (_id INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,DESCRIPTION TEXT,UNIT_COST REAL,TAXABLE INTEGER )"
    internal const val SQL_CREATE_ENTRY_ITEMS_ASSOCIATED =
        "CREATE TABLE ITEMS_ASSOCIATED (_id INTEGER PRIMARY KEY AUTOINCREMENT,ITEM_NAME TEXT,DESCRIPTION TEXT,UNIT_COST REAL,TAXABLE INTEGER,CATALOG_ID INTEGER,QTY REAL DEFAULT 1,TAX_RATE REAL,DISCOUNT REAL, FOREIGN KEY ( CATALOG_ID )  REFERENCES CATALOG ( _id ) ON DELETE CASCADE) "
    internal const val SQL_CREATE_ENTRY_PAYMENTS =
        "CREATE TABLE PAYMENTS (_id INTEGER PRIMARY KEY AUTOINCREMENT,CATALOG_ID INTEGER,AMOUNT TEXT,DATE TEXT,METHOD TEXT,NOTES TEXT, FOREIGN KEY ( CATALOG_ID )  REFERENCES CATALOG ( _id ) ON DELETE CASCADE) "
    internal const val SQL_CREATE_ENTRY_SETTINGS =
        "CREATE TABLE SETTINGS (_id INTEGER PRIMARY KEY AUTOINCREMENT,CURRENCY INTEGER DEFAULT 102 ,DATE_FORMAT INTEGER DEFAULT 0  ) "
    internal const val SQL_CREATE_ENTRY_SHIPPING =
        "CREATE TABLE SHIPPING (_id INTEGER PRIMARY KEY AUTOINCREMENT,CATALOG_ID INTEGER,AMOUNT REAL,SHIPPING_DATE TEXT,SHIP_VIA TEXT,TRACKING TEXT,FOB TEXT, FOREIGN KEY ( CATALOG_ID )  REFERENCES CATALOG ( _id ) ON DELETE CASCADE) "
    private const val TEXT_TYPE = " TEXT"
}